#!/bin/bash

usage() {
    echo 'usage: cog <package>'
}

if [[ $1 == '-h' || $1 == '--help' || $1 == '-?' ]]; then
    usage
    exit 0
fi

vars() {
    local confdir="$HOME/.config/cogrc"

    if [[ -s "$confdir" ]]; then
        . "$confdir"
    else
        die "$confdir missing"
    fi

    cwd="$PWD"

    setTrap
}

cogInstall() {
    local package="$@"

    cd "$cogdir"
    cower --download "$package"
    cd "$cogdir/$package"
    makepkg -scfi --noconfirm 
}

msg() {
    echo -e "$@"
}

die() {
    msg "error: $@"
    exit 1
}

cleanup() {
    cd "$cwd"
}

setTrap() {
    trap 'cleanup' EXIT
}

prompt() {
    while true; do
        read -p "$@ [Y/n] " yn
        case $yn in
            [Yy]* ) return 0
                ;;
            [Nn]* ) return 1
                ;;
            * ) msg 'invalid answer'
                ;;
        esac
    done
}

delegateInstall() {
    local package_list=()

    for package in $@
    do
        package_list[${#package_list[*]}]="$package"
    done

    local package_list_len=${#package_list[@]}

    if ((package_list_len == 0 )); then
        msg 'there is nothing to do'
        exit 0
    fi

    msg "Targets ($package_list_len): ${package_list[*]}"

    if prompt 'Proceed with installation?'; then

        for package in "${package_list[@]}"
        do
            if ! cogInstall "$package"; then
                msg "error: failed to install $package"
                if prompt "remove $cogdir/$package before exiting?"
                then
                    rm -rf "$cogdir/$package"
                fi

                die ''
            fi
        done

    fi
}

vars
delegateInstall "$@"
