#!/bin/bash

usage() {
    echo 'usage: cog <package>'
}

vars() {
    cogdir="$HOME/builds/cog_builds"
    currentdir="$PWD"
}

cogInstall() {
    cd "$cogdir"
    cower --download "$@"
    cd "$cogdir/$@"
    makepkg -scfi
    cd "$currentdir"
}

if [[ $1 == '-h' || $1 == '--help' || $1 == '-?' ]]; then
    usage
    exit 0
else
    vars
    cogInstall "$@"
fi
