#!/bin/bash

usage() {
    echo 'usage: cog <package>'
}

if [[ $1 == '-h' || $1 == '--help' || $1 == '-?' ]]; then
    usage
    exit 0
fi

vars() {
    cogdir="$HOME/builds/cog_builds"
    cwd="$PWD"

    setTrap
}

cogInstall() {
    local package="$@"

    cd "$cogdir"
    cower --download "$package"
    cd "$cogdir/$package"
    makepkg -scfi
}

message() {
    echo -e "$@"
}

die() {
    message "$@"
    exit 1
}

cleanup() {
    cd "$cwd"
}

setTrap() {
    trap 'cleanup' EXIT
}

prompt() {
    while true; do
        read -p "$@ [Y/n] " yn
        case $yn in
            [Yy]* ) return 0
                ;;
            [Nn]* ) return 1
                ;;
            * ) message 'invalid answer'
                ;;
        esac
    done
}

delegateInstall() {
    local package_list="$@"

    for package in "$package_list"
    do
        if ! cogInstall "$package"; then
            message "error occurred installing $package"
            if prompt "remove $cogdir/$package before exiting?"
            then
                rm -rf "$cogdir/$package"
            fi

            die ''
        fi
    done
}

vars
delegateInstall "$@"
